#include "common/utils.h"
#include "gles/GLES.h"
#include "gles/GLESExtends.h"
#include "nativeimage/NativeImage.h"
#include "napi/native_api.h"


EXTERN_C_START
static napi_value Init(napi_env env, napi_value exports) {

    /***
     * defined NativeImage
     */

    napi_property_descriptor nativeImageDesc[] = {
        DEFINE_NAPI_FUNCTION("surfaceId", nullptr, NativeImage::NapiGetSurfaceId, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("isAvailable", nullptr, NativeImage::NapiGetIsAvailable, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("attachContext", NativeImage::NapiAttachContext, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("detachContext", NativeImage::NapiDetachContext, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("destroy", NativeImage::NapiDestroyNativeImage, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("updateSurfaceImage", NativeImage::NapiUpdateSurfaceImage, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("setOnFrameAvailableListener", NativeImage::NapiSetOnFrameAvailableListener, nullptr,
                             nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("unSetOnFrameAvailableListener", NativeImage::NapiUnSetOnFrameAvailableListener, nullptr,
                             nullptr, nullptr),
    };
    DEFINE_SENDABLE_CLASS(env, exports, "NativeImage", NativeImage::NapiBindNativeImage, nativeImageDesc)
    
    /***
     * defined property
     */
    napi_property_descriptor desc[] = {
        DEFINE_NAPI_FUNCTION("glActiveShaderProgram", GLES::NapiGLActiveShaderProgram, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glActiveTexture", GLES::NapiGLActiveTexture, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glAttachShader", GLES::NapiGLAttachShader, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glBindAttribLocation", GLES::NapiGLBindAttribLocation, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glBindBuffer", GLES::NapiGLBindBuffer, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glBindFramebuffer", GLES::NapiGLBindFramebuffer, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glBindRenderbuffer", GLES::NapiGLBindRenderbuffer, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glBindTexture", GLES::NapiGLBindTexture, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glBlendColor", GLES::NapiGLBlendColor, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glBlendEquation", GLES::NapiGLBlendEquation, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glBlendEquationi", GLES::NapiGLBlendEquationi, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glBlendEquationSeparate", GLES::NapiGLBlendEquationSeparate, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glBeginTransformFeedback", GLES::NapiGLBeginTransformFeedback, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glEndTransformFeedback", GLES::NapiGLEndTransformFeedback, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glBeginQuery", GLES::NapiGLBeginQuery, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glEndQuery", GLES::NapiGLEndQuery, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glBlendFunc", GLES::NapiGLBlendFunc, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glBlendFuncSeparate", GLES::NapiGLBlendFuncSeparate, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glBlendFuncSeparatei", GLES::NapiGLBlendFuncSeparatei, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glBufferData", GLES::NapiGLBufferData, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glBufferSubData", GLES::NapiGLBufferSubData, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glCheckFramebufferStatus", GLES::NapiGLCheckFramebufferStatus, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glClear", GLES::NapiGLClear, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glClearColor", GLES::NapiGLClearColor, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glClearDepthf", GLES::NapiGLClearDepthf, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glClearStencil", GLES::NapiGLClearStencil, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glColorMask", GLES::NapiGLColorMask, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glCompileShader", GLES::NapiGLCompileShader, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glCompressedTexImage2D", GLES::NapiGLCompressedTexImage2D, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glCompressedTexSubImage2D", GLES::NapiGLCompressedTexSubImage2D, nullptr, nullptr,
                             nullptr),
        DEFINE_NAPI_FUNCTION("glCopyTexImage2D", GLES::NapiGLCopyTexImage2D, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glCopyTexSubImage2D", GLES::NapiGLCopyTexSubImage2D, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glCreateProgram", GLES::NapiGLCreateProgram, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glCreateShader", GLES::NapiGLCreateShader, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glCullFace", GLES::NapiGLCullFace, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glDeleteBuffers", GLES::NapiGLDeleteBuffers, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glDeleteVertexArrays", GLES::NapiGLDeleteVertexArrays, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glDeleteFramebuffers", GLES::NapiGLDeleteFramebuffers, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glDeleteProgram", GLES::NapiGLDeleteProgram, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glDeleteRenderbuffers", GLES::NapiGLDeleteRenderbuffers, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glDeleteShader", GLES::NapiGLDeleteShader, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glDeleteTextures", GLES::NapiGLDeleteTextures, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glDepthFunc", GLES::NapiGLDepthFunc, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glDepthMask", GLES::NapiGLDepthMask, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glDepthRangef", GLES::NapiGLDepthRangef, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glDetachShader", GLES::NapiGLDetachShader, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glDisable", GLES::NapiGLDisable, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glDisableVertexAttribArray", GLES::NapiGLDisableVertexAttribArray, nullptr, nullptr,
                             nullptr),
        DEFINE_NAPI_FUNCTION("glDrawArrays", GLES::NapiGLDrawArrays, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glDrawElements", GLES::NapiGLDrawElements, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glEnable", GLES::NapiGLEnable, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glEnableVertexAttribArray", GLES::NapiGLEnableVertexAttribArray, nullptr, nullptr,
                             nullptr),
        DEFINE_NAPI_FUNCTION("glFinish", GLES::NapiGLFinish, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glFlush", GLES::NapiGLFlush, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glFramebufferRenderbuffer", GLES::NapiGLFramebufferRenderbuffer, nullptr, nullptr,
                             nullptr),
        DEFINE_NAPI_FUNCTION("glFramebufferTexture2D", GLES::NapiGLFramebufferTexture2D, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glFrontFace", GLES::NapiGLFrontFace, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGenBuffers", GLES::NapiGLGenBuffers, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGenVertexArrays", GLES::NapiGLGenVertexArrays, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGenerateMipmap", GLES::NapiGLGenerateMipmap, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGenFramebuffers", GLES::NapiGLGenFramebuffers, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGenRenderbuffers", GLES::NapiGLGenRenderbuffers, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGenTextures", GLES::NapiGLGenTextures, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGetActiveAttrib", GLES::NapiGLGetActiveAttrib, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGetActiveUniform", GLES::NapiGLGetActiveUniform, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGetAttachedShaders", GLES::NapiGLGetAttachedShaders, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGetAttribLocation", GLES::NapiGLGetAttribLocation, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGetBooleanv", GLES::NapiGLGetBooleanv, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGetBufferParameteriv", GLES::NapiGLGetBufferParameteriv, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGetBufferParameteri64v", GLES::NapiGLGetBufferParameteri64v, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGetError", GLES::NapiGLGetError, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGetFloatv", GLES::NapiGLGetFloatv, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGetFramebufferAttachmentParameteriv", GLES::NapiGLGetFramebufferAttachmentParameteriv,
                             nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGetIntegerv", GLES::NapiGLGetIntegerv, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGetInteger64v", GLES::NapiGLGetInteger64v, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGetProgramiv", GLES::NapiGLGetProgramiv, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGetProgramInfoLog", GLES::NapiGLGetProgramInfoLog, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGetRenderbufferParameteriv", GLES::NapiGLGetRenderbufferParameteriv, nullptr, nullptr,
                             nullptr),
        DEFINE_NAPI_FUNCTION("glGetShaderiv", GLES::NapiGLGetShaderiv, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGetShaderInfoLog", GLES::NapiGLGetShaderInfoLog, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGetShaderPrecisionFormat", GLES::NapiGLGetShaderPrecisionFormat, nullptr, nullptr,
                             nullptr),
        DEFINE_NAPI_FUNCTION("glGetShaderSource", GLES::NapiGLGetShaderSource, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGetString", GLES::NapiGLGetString, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGetTexParameterfv", GLES::NapiGLGetTexParameterfv, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGetTexParameteriv", GLES::NapiGLGetTexParameteriv, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGetUniformfv", GLES::NapiGLGetUniformfv, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGetUniformiv", GLES::NapiGLGetUniformiv, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGetUniformLocation", GLES::NapiGLGetUniformLocation, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGetVertexAttribfv", GLES::NapiGLGetVertexAttribfv, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGetVertexAttribiv", GLES::NapiGLGetVertexAttribiv, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glGetVertexAttribPointerv", GLES::NapiGLGetVertexAttribPointerv, nullptr, nullptr,
                             nullptr),
        DEFINE_NAPI_FUNCTION("glHint", GLES::NapiGLHint, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glIsBuffer", GLES::NapiGLIsBuffer, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glIsEnabled", GLES::NapiGLIsEnabled, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glIsFramebuffer", GLES::NapiGLIsFramebuffer, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glIsProgram", GLES::NapiGLIsProgram, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glIsRenderbuffer", GLES::NapiGLIsRenderbuffer, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glIsShader", GLES::NapiGLIsShader, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glIsTexture", GLES::NapiGLIsTexture, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glLineWidth", GLES::NapiGLLineWidth, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glLinkProgram", GLES::NapiGLLinkProgram, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glPixelStorei", GLES::NapiGLPixelStorei, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glPolygonOffset", GLES::NapiGLPolygonOffset, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glReadPixels", GLES::NapiGLReadPixels, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glReleaseShaderCompiler", GLES::NapiGLReleaseShaderCompiler, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glRenderbufferStorage", GLES::NapiGLRenderbufferStorage, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glSampleCoverage", GLES::NapiGLSampleCoverage, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glScissor", GLES::NapiGLScissor, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glShaderBinary", GLES::NapiGLShaderBinary, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glShaderSource", GLES::NapiGLShaderSource, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glStencilFunc", GLES::NapiGLStencilFunc, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glStencilFuncSeparate", GLES::NapiGLStencilFuncSeparate, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glStencilMask", GLES::NapiGLStencilMask, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glStencilMaskSeparate", GLES::NapiGLStencilMaskSeparate, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glStencilOp", GLES::NapiGLStencilOp, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glStencilOpSeparate", GLES::NapiGLStencilOpSeparate, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glTexImage2D", GLES::NapiGLTexImage2D, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glTexParameterf", GLES::NapiGLTexParameterf, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glTexParameterfv", GLES::NapiGLTexParameterfv, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glTexParameteri", GLES::NapiGLTexParameteri, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glTexParameteriv", GLES::NapiGLTexParameteriv, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glTexSubImage2D", GLES::NapiGLTexSubImage2D, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glUniform1f", GLES::NapiGLUniform1f, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glUniform1fv", GLES::NapiGLUniform1fv, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glUniform1i", GLES::NapiGLUniform1i, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glUniform1iv", GLES::NapiGLUniform1iv, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glUniform2f", GLES::NapiGLUniform2f, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glUniform2fv", GLES::NapiGLUniform2fv, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glUniform2i", GLES::NapiGLUniform2i, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glUniform2iv", GLES::NapiGLUniform2iv, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glUniform3f", GLES::NapiGLUniform3f, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glUniform3fv", GLES::NapiGLUniform3fv, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glUniform3i", GLES::NapiGLUniform3i, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glUniform3iv", GLES::NapiGLUniform3iv, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glUniform4f", GLES::NapiGLUniform4f, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glUniform4fv", GLES::NapiGLUniform4fv, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glUniform4i", GLES::NapiGLUniform4i, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glUniform4iv", GLES::NapiGLUniform4iv, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glUniformMatrix2fv", GLES::NapiGLUniformMatrix2fv, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glUniformMatrix3fv", GLES::NapiGLUniformMatrix3fv, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glUniformMatrix4fv", GLES::NapiGLUniformMatrix4fv, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glUseProgram", GLES::NapiGLUseProgram, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glValidateProgram", GLES::NapiGLValidateProgram, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glVertexAttrib1f", GLES::NapiGLVertexAttrib1f, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glVertexAttrib1fv", GLES::NapiGLVertexAttrib1fv, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glVertexAttrib2f", GLES::NapiGLVertexAttrib2f, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glVertexAttrib2fv", GLES::NapiGLVertexAttrib2fv, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glVertexAttrib3f", GLES::NapiGLVertexAttrib3f, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glVertexAttrib3fv", GLES::NapiGLVertexAttrib3fv, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glVertexAttrib4f", GLES::NapiGLVertexAttrib4f, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glVertexAttrib4fv", GLES::NapiGLVertexAttrib4fv, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glVertexAttribPointer", GLES::NapiGLVertexAttribPointer, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glViewport", GLES::NapiGLViewport, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glBindVertexArray", GLES::NapiGLBindVertexArray, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glBindVertexBuffer", GLES::NapiGLBindVertexBuffer, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glVertexAttribFormat", GLES::NapiGLVertexAttribFormat, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glVertexAttribIFormat", GLES::NapiGLVertexAttribIFormat, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glVertexAttribBinding", GLES::NapiGLVertexAttribBinding, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glMapBufferRange", GLES::NapiGLMapBufferRange, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("glUnmapBuffer", GLES::NapiGLUnmapBuffer, nullptr, nullptr, nullptr),
        DEFINE_NAPI_FUNCTION("createShaderWithSource", GLESExtends::NapiCreateShaderWidthSource, nullptr, nullptr,
                             nullptr),
        DEFINE_NAPI_FUNCTION("glTexParameteriGroup", GLESExtends::NapiGLTexParameteriGroup, nullptr, nullptr, nullptr),
    };
    napi_define_properties(env, exports, sizeof(desc) / sizeof(desc[0]), desc);
    return exports;

}
EXTERN_C_END

static napi_module demoModule = {
    .nm_version = 1,
    .nm_flags = 0,
    .nm_filename = nullptr,
    .nm_register_func = Init,
    .nm_modname = "gles",
    .nm_priv = ((void *)0),
    .reserved = {0},
};

extern "C" __attribute__((constructor)) void RegisterGlesModule(void) { napi_module_register(&demoModule); }
